export type CountryCodes = {[name: string]: string};
export const countryCodes: CountryCodes = {
  'Aland Islands': 'AX',
  'American Samoa': 'AS',
  'Antigua and Barbuda': 'AG',
  'Antigua And Barbuda': 'AG',
  'Bosnia and Herzegovina': 'BA',
  'Bouvet Island': 'BV',
  'British Indian Ocean Territory': 'IO',
  'British Virgin Islands': 'VG',
  'Burkina Faso': 'BF',
  'Cabo Verde': 'CV',
  'Cape Verde': 'CV',
  'Caribbean Netherlands': 'DO',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Channel Islands': 'JE',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  'Dominican Republic': 'DO',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Faeroe Islands': 'FO',
  'Falkland Islands': 'FK',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  'Guinea-Bissau': 'GW',
  'Heard Island & Mcdonald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  'Hong Kong': 'HK',
  'Isle of Man': 'IM',
  'Isle Of Man': 'IM',
  'Ivory Coast': 'CI',
  'Libyan Arab Jamahiriya': 'LY',
  'Marshall Islands': 'MH',
  'Micronesia, Federated States Of': 'FM',
  'Netherlands Antilles': 'AN',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Norfolk Island': 'NF',
  'North Macedonia': 'MP',
  'Papua New Guinea': 'PG',
  'Puerto Rico': 'PR',
  'S. Korea': 'KR',
  'Saint Barthelemy': 'BL',
  'Saint Helena': 'SH',
  'Saint Kitts and Nevis': 'KN',
  'Saint Kitts And Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Martin': 'MF',
  'Saint Pierre And Miquelon': 'PM',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Sierra Leone': 'SL',
  'Sint Maarten': 'SX',
  'Solomon Islands': 'SB',
  'South Africa': 'ZA',
  'South Georgia And Sandwich Isl.': 'GS',
  'Sri Lanka': 'LK',
  'St. Barth': 'BL',
  'St. Vincent Grenadines': 'VC',
  'Svalbard And Jan Mayen': 'SJ',
  'Syrian Arab Republic': 'SY',
  'Timor-Leste': 'TL',
  'Trinidad and Tobago': 'TT',
  'Turks and Caicos': 'TC',
  'Turks And Caicos Islands': 'TC',
  'U.S. Virgin Islands': 'VI',
  'United States Outlying Islands': 'UM',
  'Vatican City': 'VA',
  'Virgin Islands, British': 'VG',
  'Wallis And Futuna': 'WF',
  'Western Sahara': 'EH',
  "Lao People's Democratic Republic": 'LA',
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  Andorra: 'AD',
  Angola: 'AO',
  Anguilla: 'AI',
  Antarctica: 'AQ',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Belize: 'BZ',
  Benin: 'BJ',
  Bermuda: 'BM',
  Bhutan: 'BT',
  Bolivia: 'BO',
  Botswana: 'BW',
  Brazil: 'BR',
  Brunei: 'BN',
  Bulgaria: 'BG',
  Burundi: 'BI',
  Cambodia: 'KH',
  Cameroon: 'CM',
  Canada: 'CA',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  Colombia: 'CO',
  Comoros: 'KM',
  Congo: 'CG',
  Croatia: 'HR',
  Cuba: 'CU',
  Curaçao: 'CW',
  Cyprus: 'CY',
  Czechia: 'CZ',
  Denmark: 'DK',
  Djibouti: 'DJ',
  Dominica: 'DM',
  DRC: 'CD',
  Ecuador: 'EC',
  Egypt: 'EG',
  Eritrea: 'ER',
  Estonia: 'EE',
  Eswatini: 'SZ',
  Ethiopia: 'ET',
  Fiji: 'FJ',
  Finland: 'FI',
  France: 'FR',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Grenada: 'GD',
  Guadeloupe: 'GP',
  Guam: 'GU',
  Guatemala: 'GT',
  Guernsey: 'GG',
  Guinea: 'GN',
  Guyana: 'GY',
  Haiti: 'HT',
  Honduras: 'HN',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  Iran: 'IR',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kiribati: 'KI',
  Korea: 'KR',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  Laos: 'LA',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Liberia: 'LR',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Libya: 'LY',
  Macao: 'MO',
  Macedonia: 'MK',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  Martinique: 'MQ',
  Mauritania: 'MR',
  Mauritius: 'MU',
  Mayotte: 'YT',
  Mexico: 'MX',
  Moldova: 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montenegro: 'ME',
  Montserrat: 'MS',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Netherlands: 'NL',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Niue: 'NU',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Palau: 'PW',
  Palestine: 'PS',
  Panama: 'PA',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Pitcairn: 'PN',
  Poland: 'PL',
  Portugal: 'PT',
  Qatar: 'QA',
  Réunion: 'RE',
  Romania: 'RO',
  Russia: 'RU',
  Rwanda: 'RW',
  'Saint Pierre Miquelon': 'PM',
  Samoa: 'WS',
  Senegal: 'SN',
  Serbia: 'RS',
  Seychelles: 'SC',
  Singapore: 'SG',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Somalia: 'SO',
  'South Sudan': 'SS',
  Spain: 'ES',
  Sudan: 'SD',
  Suriname: 'SR',
  Swaziland: 'SZ',
  Sweden: 'SE',
  Switzerland: 'CH',
  Syria: 'SY',
  Taiwan: 'TW',
  Tajikistan: 'TJ',
  Tanzania: 'TZ',
  Thailand: 'TH',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  Tunisia: 'TN',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  Tuvalu: 'TV',
  UAE: 'AE',
  Uganda: 'UG',
  UK: 'GB',
  Ukraine: 'UA',
  Uruguay: 'UY',
  USA: 'US',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Yemen: 'YE',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
};
